### ISSUE TITLE
[a11y demos] share screenrecordings

### ISSUE THREAD

**Issue by pkra** [w3c-cg/mathonwebpages#12]
From yesterdays a11y task force meeting: we want to record the behavior of the existing demos.

**Comment by pkra** [comment]
I've uploaded a set of videos for my deep-label demo (https://codepen.io/pkra/pen/xRBZjq) on youtube, playlist is at https://www.youtube.com/playlist?list=PL1ATLkPgTEBqYOb7CYz7Kv6gNHh_pXbQq.

**Comment by pkra** [comment]
@dani31415 are you planning to do some recordings we can list on the website?

**Comment by dani31415** [comment]
They are not planned.

**Comment by pkra** [comment]
copy that. I'll close this then. (There's still #15 to do.)
